name: Test

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

env:
  FORCE_COLOR: 1

jobs:
  docker-test:
    runs-on: [self-hosted, linux, ubuntu]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: mkdir -p test-results

      - name: Run tests in docker-compose
        run: docker compose run --rm playwright

      - name: Cleanup
        if: always()
        run: docker compose down

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-test-results
          path: test-results